name: ROS Build
env:
  ROS_DISTRO: 'foxy'
on:
  push:
    branches:
      - dev  # Adjust this branch name as needed

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up ROS
      uses: ros-tooling/setup-ros@v0.7
      with:
        rosdistro: humble
        colcon: true
        cmake-version: '3.16.x'
        ament-version: '2,0'

        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo apt-get -y install ament-cmake
          pip3 install colcon-common-extensions
          colcon list         
          colcon build
        
    - name: Set up ROS 2
      run: |
              sudo apt update
              sudo apt install -y python3-pip
              pip3 install -U colcon-common-extensions
              source /opt/ros/foxy/setup.bash  # Adjust to your ROS 2 distribution
      shell: bash

        
    - name: Build
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        sudo apt-get -y install ament-cmake
        pip3 install colcon-common-extensions
        colcon list         
        colcon build

    - name: Run Tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test
