name: ROS Build
env:
  ROS_DISTRO: 'foxy'
on:
  push:
    branches:
      - dev  # Adjust this branch name as needed

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
        
    - name: Build
      run: |
        sudo ./install_atos.sh 
        colcon list         
        colcon build

    - name: Run Tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test
